### ISSUE TITLE
hcloud: invalid input in field 'rules' (invalid_input)

### ISSUE THREAD

**Issue by olsp** [McPringle/mastodon-autosetup#9]
When I run the setup.sh script, I get the following error:
`hcloud: invalid input in field 'rules' (invalid_input)`

I just installed hcloud using brew. I tried to find out which part of the rules is causing this error, but the only way to get the script running without error is to remove everything inside `[]` in the firewall-config.json file.

**Comment by McPringle** [comment]
Sorry for my late reply. I did a sabbatical and since I'm back I'm very busy. There was a bug in hcloud itself. Please just update hcloud and the error should be gone.

I hope to work again on this project soon…

**Comment by McPringle** [comment]
Fixed by Hetzner
